(function(){document.documentElement.classList.add('js');var S=window.SITE||{},P=document.body.dataset.page||'home';
var L=[['Home','index.html','home'],['Menu','menu.html','menu'],['About','about.html','about'],['Offers','offers.html','offers'],['Reviews','reviews.html','reviews'],['Policies','policies.html','policies'],['Location','location.html','location']];
var a=function(x){return '<a href="'+x[1]+'"'+(x[2]==P?' class="on"':'')+'>'+x[0]+'</a>'};
var hd=document.createElement('header');hd.className='hd';
hd.innerHTML='<div class="w"><a class="logo" href="index.html" aria-label="DIP N’ STICKS home">DIP N’ <b>STICKS</b></a><nav class="nv" aria-label="Main">'+L.map(a).join('')+'</nav><a class="btn" href="location.html">Visit us</a><button class="burger" aria-label="Menu" aria-expanded="false"><i></i><i></i><i></i></button></div>';
var mm=document.createElement('div');mm.className='mm';mm.innerHTML=L.concat([['FAQ','faq.html','faq'],['Contact','contact.html','contact']]).map(a).join('')+'<a class="btn y" href="location.html">Visit us</a>';
document.body.prepend(mm);document.body.prepend(hd);
var b=hd.querySelector('.burger');b.onclick=function(){var o=mm.classList.toggle('open');b.setAttribute('aria-expanded',o);document.body.style.overflow=o?'hidden':''};
mm.querySelectorAll('a').forEach(function(x){x.addEventListener('click',function(){mm.classList.remove('open');document.body.style.overflow=''})});
addEventListener('scroll',function(){hd.classList.toggle('sm',scrollY>40)},{passive:true});
var IC={wa:'<path d="M12 3a9 9 0 0 0-7.7 13.6L3 21l4.5-1.2A9 9 0 1 0 12 3z" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/><path d="M9 8c-.5 1 0 2.6 1.6 4.2S14 14.7 15 14.2l.6-1.2-1.8-.9-.8.7c-.8-.3-1.7-1.1-2-2l.7-.8-.9-1.8z" fill="currentColor"/>',tel:'<path d="M5 4h4l2 5-2.5 1.5a11 11 0 0 0 5 5L15 13l5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2z" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/>',maps:'<path d="M12 21s7-6.2 7-11a7 7 0 0 0-14 0c0 4.8 7 11 7 11z" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="10" r="2.5" fill="currentColor"/>',clock:'<circle cx="12" cy="12" r="9" fill="none" stroke="currentColor" stroke-width="2"/><path d="M12 7v5l3 2" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>',review:'<path d="M12 3l2.7 5.6 6.1.8-4.5 4.2 1.1 6-5.4-3-5.4 3 1.1-6L3.2 9.4l6.1-.8z" fill="currentColor"/>',instagram:'<rect x="4" y="4" width="16" height="16" rx="5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="3.6" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="17" cy="7" r="1.2" fill="currentColor"/>',facebook:'<path d="M14 8h3V4h-3a4 4 0 0 0-4 4v3H7v4h3v6h4v-6h3l1-4h-4V8.5c0-.3.2-.5.5-.5z" fill="currentColor"/>',tiktok:'<path d="M14 3v11.5a3.5 3.5 0 1 1-3.5-3.5M14 3c.3 2.5 2 4 4.5 4.2" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"/>'};
var ic=function(k){return IC[k]?'<svg class="ic" viewBox="0 0 24 24" aria-hidden="true">'+IC[k]+'</svg>':''};
var D=new Date().getDay(),H=Array.isArray(S.hours)?S.hours:[],today=H[(D+6)%7];var ph=function(k){return S[k]||(S.ph&&S.ph[k])||''};
document.querySelectorAll('[data-site]').forEach(function(e){if(e.dataset.site=='hours'&&H.length){e.innerHTML='<ul class="hrs">'+H.map(function(r,i){return '<li'+(i==(D+6)%7?' class="today"':'')+'><span>'+r[0]+'</span><span>'+r[1]+'</span></li>'}).join('')+'</ul>'}else e.textContent=ph(e.dataset.site)});
document.querySelectorAll('.fi dt').forEach(function(e){var t=e.textContent.toLowerCase();e.insertAdjacentHTML('afterbegin',ic(t.indexOf('loc')==0?'maps':t.indexOf('open')==0?'clock':'tel'))});
var lk={tel:S.phone?'tel:'+S.phone.replace(/\s/g,''):'contact.html',wa:S.whatsapp||'contact.html',maps:S.maps||'location.html',review:S.reviewUrl||'reviews.html#write',instagram:(S.social||{}).instagram||'contact.html',facebook:(S.social||{}).facebook||'contact.html',tiktok:(S.social||{}).tiktok||'contact.html'};
var ft=document.createElement('footer');ft.className='ft';
ft.innerHTML='<div class="w"><div class="big">DIP N’<br>STICKS</div><p class="d" style="font-size:28px;margin-top:10px">“DIP IT. STICK IT. LOVE IT!”</p><div class="cols"><div><h4>Explore</h4>'+[['Home','index.html'],['Menu','menu.html'],['About','about.html'],['Offers','offers.html'],['Reviews','reviews.html'],['Policies','policies.html'],['FAQ','faq.html'],['Location','location.html'],['Contact','contact.html'],['Admin','/admin']].map(function(x){return '<a href="'+x[1]+'">'+x[0]+'</a>'}).join('')+'</div><div><h4>Social</h4><a href="'+lk.instagram+'">'+ic('instagram')+'Instagram</a><a href="'+lk.facebook+'">'+ic('facebook')+'Facebook</a><a href="'+lk.tiktok+'">'+ic('tiktok')+'TikTok</a></div><div><h4>Contact</h4><a href="'+lk.tel+'">'+ic('tel')+ph('phone')+'</a><a href="'+lk.wa+'">'+ic('wa')+'WhatsApp</a><a href="location.html">'+ic('maps')+ph('address')+'</a><a href="location.html">'+ic('clock')+(today?'Today: '+today[1]:'Opening hours')+'</a></div></div><p class="cp">© DIP N’ STICKS. All rights reserved.</p></div>';
document.body.appendChild(ft);
mm.insertAdjacentHTML('beforeend','<a href="/admin" style="font-size:18px;opacity:.8;margin-top:14px">Admin login</a>');
var AD=S.api?'/admin':'http://localhost:3000/admin';document.querySelectorAll('a[href="/admin"]').forEach(function(l){l.href=AD});
if(S.announcement){var an=document.createElement('div');an.className='ann';an.textContent=S.announcement;var mn=document.querySelector('main');mn.parentNode.insertBefore(an,mn)}
if(S.api){var nl=document.createElement('form');nl.className='nl';nl.innerHTML='<p class="d" style="font-size:22px;color:var(--y)">Get DIP N’ STICKS updates</p><div class="nlr"><input type="email" required placeholder="Your email" aria-label="Email for updates" maxlength="120"><button class="btn y">Subscribe</button></div><p class="nlm" role="status"></p>';
ft.querySelector('.cols').before(nl);nl.onsubmit=function(e){e.preventDefault();var m=nl.querySelector('.nlm');fetch('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:nl.querySelector('input').value})}).then(function(r){return r.json().then(function(j){m.textContent=r.ok?'Thanks for subscribing!':(j.error||'Something went wrong');if(r.ok)nl.querySelector('input').value=''})}).catch(function(){m.textContent='Could not subscribe right now.'})};
fetch('/api/whoami').then(function(r){return r.json()}).then(function(j){if(!j.admin)return;var a=document.createElement('a');a.className='admbtn';a.href=AD;var c=(j.pending||0)+(j.unread||0);a.innerHTML='⚙ Admin panel'+(c?' <b>'+c+'</b>':'');document.body.appendChild(a)}).catch(function(){});
try{navigator.sendBeacon('/api/track',new Blob([JSON.stringify({page:P})],{type:'application/json'}))}catch(x){}}
var w=document.createElement('a');w.className='wa';w.href=lk.wa;w.innerHTML=ic('wa')+'<span class="t">WhatsApp</span>';w.setAttribute('aria-label','Chat on WhatsApp');document.body.appendChild(w);
document.querySelectorAll('[data-link]').forEach(function(e){var k=e.dataset.link;e.href=lk[k]||'#';if(/^https?:/.test(e.href))e.target='_blank',e.rel='noopener';e.insertAdjacentHTML('afterbegin',ic(k))});
})();
